### ISSUE TITLE
PDF Layout for the book

### ISSUE THREAD

**Issue by PatMis16** [bioimagebook/bioimagebook.github.io#14]
Hi,
This is not an issue but a question. How do I control the layout for the PDF version of the book? I am asking this because I want to write a book myself.
Thank you!
 
Best regards,
Patrick

**Comment by petebankhead** [comment]
I don't know any more than is included in the Jupyter Book docs at https://jupyterbook.org/en/stable/advanced/pdf.html

I haven't tried to make a PDF version myself, because of the effort I suspect would be involved in formatting it.
