### ISSUE TITLE
adding standard deviations from two random variables

### ISSUE THREAD

**Issue by stephenogg** [bioimagebook/bioimagebook.github.io#24]
I noticed in your chapter on noise, in the section where you are describing your important noise facts, that your formula for adding the standard deviations from two random variables has a typo, I think.  Each standard deviation needs to be squared before adding - add the variances and then take the square root to calculate the sigma for the sum of two random variables.

You have this: $\sqrt{\sigma_1 + \sigma_2}$
should be this: $\sqrt{\sigma_1^2 + \sigma_2^2}$

Brilliant book! Thank you for your hard work to make these topics accessible to biologists

**Comment by petebankhead** [comment]
Ah, well-spotted, thanks!

Should be fixed now in this section https://bioimagebook.github.io/chapters/3-fluorescence/3-formation_noise/formation_noise.html#background

If you spotted it somewhere else, please let me know.
