### ISSUE TITLE
copyright statement

### ISSUE THREAD

**Issue by haesleinhuepf** [bioimagebook/bioimagebook.github.io#28]
Hi Pete @petebankhead .,

just a minor headsup regarding licensing. I see the book has a CC BY 4.0 tag, but it is missing a LICENSE file. If it had that, the github repository would show the license correctly. Similarly, the footer of the book could show the license correctly as done [here](https://github.com/haesleinhuepf/BioImageAnalysisNotebooks/blob/51de3ebc1f5b9417c02fa2f132aea469dc045c2b/docs/_config.yml#L31-L38). At the moment it looks like this:

![image](https://github.com/bioimagebook/bioimagebook.github.io/assets/12660498/e860c528-e736-4c09-b552-0410e2c28cc6)

If you think this makes sense, I'm happy to prepare a PR for you.

Thanks for maintaining this amazing resource btw!

Best,
Robert

**Comment by petebankhead** [comment]
Thanks @haesleinhuepf ! I'll update the copyright statement.

As well as the tag, there is a 'License' statement as a page on its own (you can see it in your screenshot, on the left).

**Comment by petebankhead** [comment]
Updated now, thanks!

**Comment by haesleinhuepf** [comment]
awesome, thanks for the quick response and have a great weekend!
